### ISSUE TITLE
Saving root data that is pulled from OpenData

### ISSUE THREAD

**Issue by codecalec** [keaveney/UCT3rdYearLabATLASOpenData#1]
Hi,

Would it be possible to change the way data is pulled from OpenData?
At the moment, data is pulled but not save locally in part 1.

I've made changes for myself. I can do a pull request if you think this won't break any Binder interactions.

Regards
Alex

**Comment by keaveney** [comment]
Hi Alex,
  I don't fully understand the question. Are you looking at the "2020" branch? There the root files are actually part of the repo. This make things much more smooth and fast on mybinder. Streaming files over http is slow.

Not sure that is what you are suggesting though?

James

**Comment by codecalec** [comment]
[Near the top](https://github.com/keaveney/UCT3rdYearLabATLASOpenData/blob/master/Part1_MeasureTheZBosonMass.ipynb) you retrieve a large file. 

I've changed it to [this](https://github.com/codecalec/UCT3rdYearLabATLASOpenData/blob/master/Part1_MeasureTheZBosonMass.ipynb).

Are these files in the repo already?

**Comment by keaveney** [comment]
That's the master branch, you should be looking at the "2020" branch, there the root files are included in the repo and read as such, so no need for any streaming/downloading/saving.

**Comment by codecalec** [comment]
That makes way more sense. Sorry for the hassle.
